### ISSUE TITLE
Unable to run built web version (App.js / dry-di)

### ISSUE THREAD

**Issue by Nedgeva** [felipemanga/ProjectABE#42]
Hello!

Changes in the source of 'App.js' after [#1246c8996b108c286c1fae5d9e7cdf08cfd9f81c](https://github.com/felipemanga/ProjectABE/commit/1246c8996b108c286c1fae5d9e7cdf08cfd9f81c#diff-14b1e33d5bf5649597cdc0e4f684dadd) commit causes following error in browser after web version is built:
> Uncaught Error: No viable providers for App. #126

After reverting back changes to previous version app runs without any problem.

**Comment by felipemanga** [comment]
Sorry about that... the current master is going through a major refactor. Since I'm generally the only one messing with the code and fixes are quick, nobody generally notices when I break master. :stuck_out_tongue:

If you don't mind me asking, is there any reason why you're building from source? Just trying to better understand how people use ABE.
